# Generated by Django 5.0.6 on 2024-06-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_solicitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asunto', models.CharField(max_length=200)),
                ('Describa_su_solicitud', models.TextField(blank=True)),
                ('Guardar', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
