# Generated by Django 5.0.6 on 2024-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_crear_solicitude_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Cedula', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=12)),
            ],
        ),
    ]
