# Generated by Django 5.0.6 on 2024-06-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_usuario_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Cedula',
        ),
    ]
