# Generated by Django 5.0.6 on 2024-06-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Cedula',
            field=models.IntegerField(default=15),
        ),
    ]
