# Generated by Django 5.0.6 on 2024-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_usuario_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_equipo', models.CharField(max_length=200)),
                ('Marca_del_dispositivo', models.CharField(max_length=150)),
                ('Modelo_del_equipo', models.CharField(max_length=150)),
                ('Numero_serial', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero',
            new_name='Numero',
        ),
    ]
