# Generated by Django 5.0.6 on 2024-06-23 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_dispositivos_rename_correo_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
