# Generated by Django 5.0.6 on 2024-06-23 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cedula',
            field=models.IntegerField(max_length=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
