# Generated by Django 5.0.6 on 2024-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Administracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='IE_BILBAO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='IE_CHUNIZA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='IE_LA_ESTRELLITA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='IE_SAN_JOSE',
            field=models.BooleanField(default=False),
        ),
    ]
