# Generated by Django 5.0.6 on 2024-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_usuario_administracion_usuario_ie_bilbao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('Numero_caso', models.AutoField(primary_key=True, serialize=False)),
                ('Persona_quien_lo_atiende_Julian_Albarracin', models.BooleanField(default=False)),
            ],
        ),
    ]
