# Generated by Django 5.0.6 on 2024-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_asignado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Persona_quien_lo_atiende_Julian_Albarracin',
            field=models.BooleanField(default=False),
        ),
    ]
