# Generated by Django 5.0.6 on 2024-06-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_delete_asignado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crear_solicitude',
            old_name='Guardar',
            new_name='Persona_quien_lo_atiende_Julian_Albarracin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Persona_quien_lo_atiende_Julian_Albarracin',
        ),
    ]
