# Generated by Django 5.0.6 on 2024-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_rename_persona_quien_lo_atiende_julian_albarracin_crear_solicitude_asignado_a_julian_albarracin_and_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear_solicitude',
            name='Asignado_a_Julian_Albarracin',
            field=models.BooleanField(default=True),
        ),
    ]
