# Generated by Django 5.0.6 on 2024-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Almacen', models.BooleanField(default=False)),
                ('AudioVisuales', models.BooleanField(default=False)),
                ('Biblioteca', models.BooleanField(default=False)),
                ('Cord_Academica', models.BooleanField(default=False)),
                ('Cord_Convivencia', models.BooleanField(default=False)),
                ('Cuarto_Camaras', models.BooleanField(default=False)),
                ('Deposito', models.BooleanField(default=False)),
                ('Emisora', models.BooleanField(default=False)),
                ('Enfermeria', models.BooleanField(default=False)),
                ('Laboratorio_Biologia', models.BooleanField(default=False)),
                ('Laboratorio_Fisica', models.BooleanField(default=False)),
                ('Laboratorio_Quimica', models.BooleanField(default=False)),
                ('Oratorio', models.BooleanField(default=False)),
                ('Pastoral', models.BooleanField(default=False)),
                ('Psicologia', models.BooleanField(default=False)),
                ('Rectoria', models.BooleanField(default=False)),
                ('Secretaria', models.BooleanField(default=False)),
                ('Sala_Docentes', models.BooleanField(default=False)),
                ('Tecnologia_Primaria', models.BooleanField(default=False)),
                ('Tecnologia_Bachillerato', models.BooleanField(default=False)),
                ('Trabajo_Social', models.BooleanField(default=False)),
                ('Otro', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='Almacenista',
            field=models.BooleanField(default=False),
        ),
    ]
